config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root             'static_pages#home'
  get 'home'    => 'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  # In the code block below, the RESTful URLs and route names for the GET 
  # action look like this:
  
  #   URL  route name
  
  #   /users/1/following  following_user_path(1)
  #   /users/1/followers  followers_user_path(1)

  resources :users do
    member do
      get :following, :followers   # correspond to actions in users_controller.rb
    end
  end
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  
  # For following and unfollowing a user (create via form, destroy via form)
  resources :relationships,       only: [:create, :destroy]
  
  
  # The above "resources :users" entry adds the following actions and routes automatically:
  
  # Action Route Method
  # index users_path GET
  # show user_path(user) GET
  # new new_user_path GET
  # create users_path POST
  # edit edit_user_path(user) GET
  # update user_path(user) PATCH
  # destroy user_path(user) DELETE
  
  # The above "resources :password_resets" entry adds the following actions and RESTful routes:
  
  # METHOD - URL - Action - Named route
  
  # GET	/password_resets/new	new	new_password_reset_path
  # POST	/password_resets	create	password_resets_path
  # GET	/password_resets/<token>/edit	edit	edit_password_reset_path(token)
  # PATCH	/password_resets/<token>	update	password_reset_path(token)
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController


  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end


  def help
  end


  def about
  end


  def contact
  end
  
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_home_logged_in.html.erb
  <div class="row">

    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>

      <section class="stats">
        <%= render 'shared/stats' %>
      </section>

      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    
    <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
    
  </div>

app/views/static_pages/_home_logged_out.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <h2>
    For Steve's info about this project, including source code, please see the 
    <%= link_to "About", about_path %>
    page.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>

<p>
  The sample Twitter-like micropost application at this site has been put 
  together by Steve Swett by  following Michael Hartl's Ruby on Rails tutorial 
  -- a book over 750 pages in PDF  format.  The design and code are Mr. Hartl's.
</p>

<p>
  So, what can you do with the app? 
  <ul>
    <li>
      Create your own user account by signing up from the Home page
    </li>
    <li>
      After receiving an account activation e-mail, activate your account
    </li>
    <li>
      While logged in, create microposts (brief text entries with optional 
      image uploads) from the Home page
    </li>
    <li>
      Visit the Users page to follow the microposts of other users
    </li>
  </ul>
</p>

<p>
  Try it!
</p>

<p>
  Technologies: AWS S3 for cloud-based image storage, Mandrill for e-mail, 
  Cloud 9 IDE for development, Git for version control, Bitbucket for remote 
  repositories, Heroku for production deployment
</p>

<p>
  The source code to this project can be found <a href="https://bitbucket.org/sswett/sample_app">here</a>.
</p>

<p>
  &nbsp;
</p>

<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/#contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/#help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>  

app/views/static_pages/home.html.erb
<% if logged_in? %>

  <%= render 'static_pages/home_logged_in' %>

<% else %>

  <%= render 'static_pages/home_logged_out' %>

<% end %>            